# -*- coding: utf-8 -*-
"""Promedio_JCPS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZl3k1vaZe7r5E3IX1dK4bIA-aSJSZXm
"""

def calcular_promedio(lista_numeros):
    """
    Calcula el promedio de una lista de números.

    Parámetros:
    lista_numeros (list): Lista que contiene números (int o float).

    Retorna:
    float: El promedio de los números en la lista.

    Ejemplo:
    >>> calcular_promedio([4, 8, 6])
    6.0
    """
    if not lista_numeros:
        return 0  # Evita división por cero si la lista está vacía
    return sum(lista_numeros) / len(lista_numeros)

# Ejemplo de uso
numeros = [4, 8, 6]
promedio = calcular_promedio(numeros)
print("El promedio es:", promedio)